services:
  mysql:
    image: mysql:8.0
    container_name: garage-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    build: ./backend
    container_name: garage-management-express-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - mysql
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: garage-management-react-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: garage-management-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

volumes:
  mysql:
  redis-data:
  backend_node_modules:
  frontend_node_modules: